### ISSUE TITLE
Ubuntu 16.04, ROS Kinetic: error: sphero_node/SpheroCollision.h: No such file or directory

### ISSUE THREAD

**Issue by defied** [eborghi10/Sphero-ROS#1]
/home/defied/catkin_ws/src/Sphero-ROS/gazebo_contact_sensor_plugin/src/ContactPlugin.cpp:2:41: fatal error: sphero_node/SpheroCollision.h: No such file or directory
compilation terminated.

**Comment by ritesh2014** [comment]
I am getting the same error

**Comment by smithan7** [comment]
Same error

**Comment by smithan7** [comment]
Was able to fix by removing the 'gazebo_contact_sensor_plugin' folder outside of catkin_ws/src/Sphero-ROS, then running catkin_make. This compiled the missing msg creating the missing .h file. Then, put 'gazebo_contact_sensor_plugin' folder back in catkin_ws/src/Sphero-ROS and doing catkin_make again. Then it makes correctly. There is probably a cleaner way to do it by listing dependencies but this was fast and only needs to be done once.

**Comment by eborghi10** [comment]
Sorry for the belated response, @defied @ritesh2014 @smithan7. I fixed the issue in the referenced commit. I also added support for Gazebo 9 and fixed some issues spawning the desert model.

HTH.
