### ISSUE TITLE
Error libgazebo_sphero_controller.so: undefined symbol: _ZN6gazebo9GazeboRos19readCommonParameterEv

### ISSUE THREAD

**Issue by florianspy** [eborghi10/Sphero-ROS#3]
I go the above error when i start your program. It is fixible when adding in your CmakeLists.txt (Sphero-ROS/sphero_gazebo/CMakeLists.txt) inside target_link_libraries the following line /opt/ros/kinetic/lib/libgazebo_ros_utils.so or /opt/ros/melodic/lib/libgazebo_ros_utils.so

**Comment by eborghi10** [comment]
Fixed, thanks for reporting it, @florianspy!
